---
title: "Untitled"
author: "JfMra"
date: "14/2/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Considere la base de datos sleepstudy del paquete lme4. El objetivo es comparar los siguientes dos modelos.
```{r}
library(lme4)
data(sleepstudy)
```

$$H_0: \beta_2 = 0 \;\; v.s \;\; H_1: B_2 \not=0 $$
Sinedo $B_2$ el termino que acompaña al termino cuadratico
```{r}
mod1 <- lmer(Reaction~Days + (Days|Subject) , data = sleepstudy)

mod2 <- lmer(Reaction~Days+I(Days^2) + (1 + Days |Subject), data = sleepstudy)
```

```{r}
anova(mod1, mod2)
```


```{r}
nrep <- 5000
lrts_lme4 <- numeric(nrep)
for (i in 1:nrep) {
  new_y_h0 <- simulate(mod1) # Asumiendo H0 verdadera
  sleepstudy$new_y_h0 <- new_y_h0$sim_1
  aux0 <- lmer(new_y_h0 ~ Days + (1+Days|Subject), data=sleepstudy, REML=FALSE)
  aux1 <- lmer(new_y_h0 ~ Days +Days^2 + (1+Days|Subject), data=sleepstudy, REML=FALSE)
  lrts_lme4[i] <- -2 * (logLik(aux0) - logLik(aux1))
}
```


